version: "3"
services: 
  appa:
    image: nginx:1.12.2-alpine
    volumes:
      - ./.conf/nginx-a.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:8001"
  appb:
    image: nginx:1.12.2-alpine
    volumes:
      - ./.conf/nginx-b.conf:/etc/nginx/nginx.conf
    ports:
      - "3001:8002"

  