version: "3"
services: 
  appa:
    image: nginx:1.12.2-alpine
    volumes:
      - ./.conf/nginx-a.conf:/etc/nginx/nginx.conf

  appb:
    image: nginx:1.12.2-alpine
    volumes:
      - ./.conf/nginx-b.conf:/etc/nginx/nginx.conf

  appresty:
    image: openresty/openresty:alpine
    volumes: 
      - ./.conf/openresty.conf:/usr/local/openresty/nginx/conf/nginx.conf
    links:
      - appa
      - appb
    ports: 
      - "8080:8003"